[tool.poetry]
name = "github-notifications-cleaner"
version = "0.2.0"
description = ""
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.scripts]
github-notifications-cleaner = "github_notifications_cleaner.__main__:cli"
github-billing-user = "github_notifications_cleaner.billing:cli"

[tool.poetry.dependencies]
python = "^3.9"
PyGithub = "^1.59"
click = "^8.1.4"
loguru = "^0.7.0"
pydantic-settings = "^2.0.2"

[tool.poetry.dependencies.pydantic]
extras = [
    "dotenv",
]
version = "^2.0.3"

[tool.poetry.dev-dependencies]
mypy = "^1.4"
pytest = "^7.4.0"
black = "^23.7.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.278"
types-click = "^7.1.8"

[tool.pylint.MASTER]
max-line-length = 200

[tool.ruff]
line-length = 200

[tool.mypy]
plugins = "pydantic.mypy"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
