[tool.poetry]
name = "github-notifications-cleaner"
version = "0.1.0"
description = ""
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.scripts]
github-notifications-cleaner = "github_notifications_cleaner.__main__:cli"
github-billing-user = "github_notifications_cleaner.billing:cli"

[tool.poetry.dependencies]
python = "^3.9"
PyGithub = "^1.58"
click = "^8.1.3"
loguru = "^0.6.0"

[tool.poetry.dependencies.pydantic]
extras = [
    "dotenv",
]
version = "^1.10.6"

[tool.poetry.dev-dependencies]
pylint = "^2.17.0"
mypy = "^1.0"
pytest = "^7.2.2"
black = "^23.1.0"

[tool.pylint.MASTER]
max-line-length = 200

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
